language: python

python:
  - '3.6'

env:
  global:
    - BOTO_CONFIG=/dev/null
    - AWS_ACCESS_KEY_ID=dummy-access-key
    - AWS_SECRET_ACCESS_KEY=dummy-access-key-secret
    - AWS_DEFAULT_REGION=us-east-1

install:
  - python -m pip install -r requirements.txt
  - python -m pip list

script:
  - python -m pytest tests/
